import { makePsyche } from "./psyche"
import type { Persona } from "./types"

// Fernhollow's fifteen founders (docs/society-spec.md sections 3.1 to 3.5).
// Twelve working adults, one retired elder and two school children. No driver
// is central: each brings a different mix, and some are deliberately paired
// against each other (the ambitious mayor and the principled builder, the rule
// bound officer and the liberty loving innkeeper, the altruist doctor and the
// Machiavellian shopkeeper who controls the food supply).

const needs = (hunger: number, thirst: number, energy: number, social: number, fun: number, purpose: number, respect: number) => ({
  hunger,
  thirst,
  energy,
  health: 100,
  social,
  fun,
  purpose,
  respect,
})

export const PERSONAS: Persona[] = [
  {
    id: "tomas",
    name: "Tomas",
    surname: "Vale",
    age: 44,
    job: "mayor",
    vocation: "mayor",
    blurb: "A gifted builder who went into politics and likes his work to be noticed.",
    colors: { hair: "#2a2a34", skin: "#d9a57a", shirt: "#2f9e9a", pants: "#34343e" },
    psyche: makePsyche({
      big5: { conscientiousness: 75, extraversion: 72, agreeableness: 38 },
      values: { achievement: 82, power: 70, stimulation: 66, benevolence: 35 },
      attachment: "anxious",
      dark: { narcissism: 72, machiavellianism: 40 },
      risk: 62,
    }),
    decay: {},
    start: needs(65, 60, 80, 55, 50, 50, 45),
    coins: 120,
  },
  {
    id: "odile",
    name: "Odile",
    surname: "Marsh",
    age: 42,
    job: "police_officer",
    vocation: "police officer",
    blurb: "Has worn the badge for twelve years and believes a town without order is no town at all.",
    colors: { hair: "#5a3a6a", skin: "#f4d2b4", shirt: "#ece4cc", pants: "#5a4a3a" },
    psyche: makePsyche({
      big5: { conscientiousness: 72, agreeableness: 45, openness: 25 },
      values: { tradition: 88, conformity: 82, security: 70, universalism: 15, stimulation: 20 },
      foundations: { sanctity: 90, authority: 85, loyalty: 85, liberty: 25 },
      attachment: "secure",
      trust: 45,
    }),
    decay: { energy: 1.1 },
    start: needs(65, 65, 80, 60, 55, 60, 65),
    coins: 60,
  },
  {
    id: "hazel",
    name: "Hazel",
    surname: "Quill",
    age: 47,
    job: "doctor",
    vocation: "doctor",
    blurb: "The town doctor for twenty years; she has delivered half the people in Fernhollow.",
    colors: { hair: "#8a8a90", skin: "#c68a5e", shirt: "#ffffff", pants: "#3a6a5a" },
    psyche: makePsyche({
      big5: { openness: 60, conscientiousness: 75, extraversion: 55, agreeableness: 90, neuroticism: 35 },
      values: { benevolence: 90, universalism: 80, achievement: 62, power: 15 },
      foundations: { care: 90, fairness: 85, authority: 30 },
      attachment: "secure",
      dark: { machiavellianism: 5, narcissism: 10, psychopathy: 3 },
      risk: 30,
      patience: 70,
      trust: 70,
    }),
    decay: {},
    start: needs(65, 70, 70, 60, 55, 70, 60),
    coins: 150,
  },
  {
    id: "ivy",
    name: "Ivy",
    surname: "Harrow",
    age: 31,
    job: "nurse",
    vocation: "nurse",
    blurb: "Came to Fernhollow to nurse at the clinic, married Pip, and still misses the bustle of the city.",
    colors: { hair: "#c0503a", skin: "#f2c4a0", shirt: "#f4f0e8", pants: "#5a7ab8" },
    psyche: makePsyche({
      big5: { openness: 50, conscientiousness: 45, extraversion: 62, agreeableness: 70, neuroticism: 62 },
      values: { benevolence: 76, hedonism: 70, stimulation: 62, tradition: 30 },
      foundations: { care: 80, loyalty: 72, sanctity: 28 },
      attachment: "anxious",
      dark: { machiavellianism: 15, narcissism: 38, psychopathy: 5 },
      risk: 45,
      patience: 40,
    }),
    decay: {},
    start: needs(55, 60, 65, 55, 45, 55, 50),
    coins: 35,
  },
  {
    id: "linnea",
    name: "Linnea",
    surname: "Fairbanks",
    age: 33,
    job: "teacher",
    vocation: "teacher",
    blurb: "Teaches every child in town in one room and believes each of them can go far.",
    colors: { hair: "#e8c060", skin: "#f5d0b0", shirt: "#6ab0a0", pants: "#4a4a6a" },
    psyche: makePsyche({
      big5: { openness: 85, conscientiousness: 70, extraversion: 55, agreeableness: 80, neuroticism: 35 },
      values: { universalism: 86, benevolence: 80, selfDirection: 75, power: 15 },
      foundations: { fairness: 90, care: 85, liberty: 72, authority: 30 },
      attachment: "secure",
      dark: { machiavellianism: 5, narcissism: 10, psychopathy: 3 },
      risk: 45,
      patience: 75,
      trust: 65,
    }),
    decay: {},
    start: needs(65, 65, 75, 60, 60, 60, 55),
    coins: 50,
  },
  {
    id: "juniper",
    name: "Juniper",
    surname: "Moss",
    age: 24,
    job: "journalist",
    vocation: "journalist",
    blurb: "Prints the Fernhollow Crier on an old press and cannot leave a question unasked.",
    colors: { hair: "#2e2a3a", skin: "#c68a5e", shirt: "#58b858", pants: "#7a4a2a" },
    psyche: makePsyche({
      big5: { openness: 90, extraversion: 45, conscientiousness: 35 },
      values: { selfDirection: 86, stimulation: 80, universalism: 66, conformity: 25 },
      foundations: { liberty: 82 },
      attachment: "avoidant",
      risk: 70,
    }),
    decay: { energy: 1.1 },
    start: needs(65, 55, 90, 70, 35, 55, 55),
    coins: 25,
  },
  {
    id: "wren",
    name: "Wren",
    surname: "Aldous",
    age: 41,
    job: "carpenter",
    vocation: "carpenter",
    blurb: "Learned the trade from Bram; most of the porches on Elm Lane are hers.",
    colors: { hair: "#a8482c", skin: "#f2c6a0", shirt: "#e8893a", pants: "#4a3a2a" },
    psyche: makePsyche({
      big5: { conscientiousness: 85, agreeableness: 62, extraversion: 40, neuroticism: 35 },
      values: { achievement: 80, tradition: 70, benevolence: 68, hedonism: 30 },
      foundations: { fairness: 80, care: 65 },
      attachment: "secure",
      dark: { narcissism: 45 },
      patience: 85,
    }),
    decay: {},
    start: needs(70, 70, 85, 60, 55, 55, 60),
    coins: 70,
  },
  {
    id: "sable",
    name: "Sable",
    surname: "Crane",
    age: 39,
    job: "shopkeeper",
    vocation: "shopkeeper",
    blurb: "A sharp, ambitious trader who took over the general store and doubled its business.",
    colors: { hair: "#1c1c22", skin: "#e2b894", shirt: "#7a2438", pants: "#24242c" },
    psyche: makePsyche({
      big5: { agreeableness: 15, conscientiousness: 62, extraversion: 55 },
      values: { power: 86, achievement: 76, security: 60, benevolence: 20, universalism: 25 },
      foundations: { care: 25, fairness: 30 },
      attachment: "avoidant",
      dark: { machiavellianism: 85, narcissism: 60, psychopathy: 38 },
      patience: 80,
      risk: 70,
      trust: 28,
    }),
    decay: {},
    start: needs(60, 60, 80, 55, 55, 50, 55),
    coins: 280,
  },
  {
    id: "mo",
    name: "Mo",
    surname: "Harrow",
    age: 29,
    job: "cook",
    vocation: "cook",
    blurb: "Pip's sister; runs the Kettle diner and notices who has not eaten.",
    colors: { hair: "#e8b83a", skin: "#e8b48a", shirt: "#4aa0e0", pants: "#4a4a58" },
    psyche: makePsyche({
      big5: { extraversion: 85, agreeableness: 85, neuroticism: 58 },
      values: { benevolence: 88, conformity: 70, tradition: 60, power: 25 },
      foundations: { care: 88, loyalty: 80 },
      attachment: "anxious",
      trust: 70,
    }),
    decay: {},
    start: needs(70, 60, 80, 40, 60, 55, 60),
    coins: 80,
  },
  {
    id: "lark",
    name: "Lark",
    surname: "Bellamy",
    age: 30,
    job: "innkeeper",
    vocation: "innkeeper",
    blurb: "Keeps the Rusty Lantern loud and late; would rather start a party than follow a rule.",
    colors: { hair: "#e86aa0", skin: "#d9a07a", shirt: "#f08cc8", pants: "#3a3a6a" },
    psyche: makePsyche({
      big5: { openness: 86, extraversion: 82, conscientiousness: 30 },
      values: { selfDirection: 86, universalism: 70, hedonism: 66, conformity: 18, tradition: 30 },
      foundations: { liberty: 90, authority: 15 },
      attachment: "secure",
      risk: 65,
    }),
    decay: {},
    start: needs(65, 60, 80, 55, 45, 55, 55),
    coins: 85,
  },
  {
    id: "pip",
    name: "Pip",
    surname: "Harrow",
    age: 34,
    job: "farmer",
    vocation: "farmer",
    blurb: "A careful farmer who grew up on the Harrow land and worries when the pantry runs low.",
    colors: { hair: "#6b3e26", skin: "#f5c9a0", shirt: "#e0584a", pants: "#3b4a8c" },
    psyche: makePsyche({
      big5: { neuroticism: 76, conscientiousness: 66, openness: 30 },
      values: { security: 86, tradition: 70, benevolence: 64, stimulation: 25 },
      foundations: { loyalty: 72 },
      attachment: "anxious",
      risk: 15,
      patience: 70,
    }),
    decay: { hunger: 1.3 },
    start: needs(45, 70, 85, 60, 55, 55, 55),
    coins: 30,
  },
  {
    id: "hollis",
    name: "Hollis",
    surname: "Reed",
    age: 26,
    job: "fisher",
    vocation: "fisher",
    blurb: "A charming fisher who loves a good time more than a hard day.",
    colors: { hair: "#c2762e", skin: "#f0c090", shirt: "#e8c83a", pants: "#3a5a8a" },
    psyche: makePsyche({
      big5: { conscientiousness: 15, extraversion: 72, agreeableness: 60 },
      values: { hedonism: 86, stimulation: 70, conformity: 25, achievement: 25 },
      attachment: "secure",
      patience: 15,
      risk: 60,
    }),
    decay: { energy: 0.9 },
    start: needs(40, 55, 75, 55, 45, 50, 55),
    coins: 6,
  },
  {
    id: "bram",
    name: "Bram",
    surname: "Oakes",
    age: 68,
    job: null,
    vocation: "retired carpenter",
    blurb: "The oldest soul in town: grumpy, kind, fond of naps; he sweeps the chapel steps.",
    colors: { hair: "#b8b8c0", skin: "#f0c8a8", shirt: "#9a6ac8", pants: "#3a3a44" },
    psyche: makePsyche({
      big5: { agreeableness: 66, extraversion: 25, neuroticism: 45, openness: 38 },
      values: { tradition: 78, benevolence: 70, security: 66, stimulation: 22 },
      foundations: { sanctity: 62, authority: 60 },
      attachment: "secure",
      patience: 75,
    }),
    decay: { energy: 1.4 },
    start: needs(60, 65, 55, 70, 60, 50, 70),
    coins: 90,
  },
  {
    id: "kit",
    name: "Kit",
    surname: "Harrow",
    age: 9,
    job: null,
    vocation: "schoolboy",
    blurb: "Nine years old, quiet, and always asking how things work.",
    colors: { hair: "#6b3e26", skin: "#f5c9a0", shirt: "#f0b030", pants: "#3b4a8c" },
    psyche: makePsyche({
      big5: { openness: 55, conscientiousness: 50, extraversion: 40, agreeableness: 60, neuroticism: 62 },
      dark: { machiavellianism: 15, psychopathy: 10 },
      patience: 40,
      trust: 60,
    }),
    decay: { hunger: 1.15, energy: 1.1 },
    start: needs(50, 65, 90, 60, 50, 55, 50),
    coins: 2,
  },
  {
    id: "tansy",
    name: "Tansy",
    surname: "Harrow",
    age: 6,
    job: null,
    vocation: "schoolgirl",
    blurb: "Six years old and loud about it; happiest when everyone is watching.",
    colors: { hair: "#c0503a", skin: "#f2c4a0", shirt: "#e878b0", pants: "#5a4a8c" },
    psyche: makePsyche({
      big5: { openness: 45, conscientiousness: 55, extraversion: 62, agreeableness: 55, neuroticism: 52 },
      dark: { machiavellianism: 10, psychopathy: 5 },
      risk: 55,
      patience: 35,
      trust: 65,
    }),
    decay: { hunger: 1.15, energy: 1.1 },
    start: needs(55, 60, 90, 65, 45, 50, 50),
    coins: 0,
  },
]

export const isChild = (p: Persona) => p.age < 16

/** Founding liking between two founders, directed from `from` to `to` (spec 3.5). */
export function foundingAffinity(from: Persona, to: Persona): number {
  const ties: Record<string, number> = {
    "pip>ivy": 0.8,
    "ivy>pip": 0.8,
    "pip>kit": 0.9,
    "pip>tansy": 0.9,
    "ivy>kit": 0.9,
    "ivy>tansy": 0.9,
    "kit>pip": 0.9,
    "tansy>pip": 0.9,
    "kit>ivy": 0.9,
    "tansy>ivy": 0.9,
    "kit>tansy": 0.5,
    "tansy>kit": 0.5,
    "pip>mo": 0.7,
    "mo>pip": 0.7,
    "mo>ivy": 0.6,
    "mo>kit": 0.6,
    "mo>tansy": 0.6,
    "wren>bram": 0.6,
    "bram>wren": 0.5,
    "wren>tomas": -0.1,
    "tomas>wren": -0.1,
    "tomas>odile": 0.4,
    "odile>tomas": 0.5,
    "sable>tomas": 0.3,
    "tomas>sable": 0.3,
    "juniper>tomas": -0.2,
    "tomas>juniper": -0.1,
    "odile>lark": -0.2,
    "lark>odile": -0.05,
    "odile>juniper": -0.1,
    "lark>hollis": 0.4,
    "hollis>lark": 0.4,
    "hazel>ivy": 0.4,
    "ivy>hazel": 0.4,
    "linnea>kit": 0.5,
    "linnea>tansy": 0.5,
    "kit>linnea": 0.4,
    "tansy>linnea": 0.4,
    "hollis>sable": -0.2,
  }
  const key = `${from.id}>${to.id}`
  if (key in ties) return ties[key]
  if (to.id === "bram") return 0.35
  if (from.id === "mo" && !isChild(to)) return 0.3
  return isChild(from) || isChild(to) ? 0.1 : 0.15
}

/** Founding memories the spec gives as lines rather than ledger entries in this slice. */
export const FOUNDING_MEMORIES: Record<string, string[]> = {
  sable: ["You paid for Tomas's election campaign, and he owes you a favour."],
  tomas: ["Sable paid for your election campaign, and you owe him a favour."],
  hollis: ["You owe the general store 30 coins from last month and have not paid it back."],
  odile: ["Tomas appointed you chief of police."],
  wren: ["Bram taught you the carpenter's trade."],
}
