import { makePsyche } from "./psyche"
import type { Persona } from "./types"

// Ten founders with deliberately different psychologies. No driver is central:
// builders, carers, an anxious provider, an explorer, an elder, a schemer, a
// free-rider, a zealot and a free spirit share one small village and one store.

const body = (hunger: number, thirst: number, energy: number) => ({ hunger, thirst, energy, health: 100 })

export const PERSONAS: Persona[] = [
  {
    id: "wren",
    name: "Wren",
    vocation: "builder",
    craft: "build",
    blurb: "The village's most dependable builder, proud of work done properly.",
    colors: { hair: "#a8482c", skin: "#f2c6a0", shirt: "#e8893a", pants: "#4a3a2a" },
    psyche: makePsyche({
      big5: { conscientiousness: 85, agreeableness: 62, extraversion: 40, neuroticism: 35 },
      values: { achievement: 80, tradition: 70, benevolence: 68, hedonism: 30 },
      foundations: { fairness: 80, care: 65 },
      attachment: "secure",
      dark: { narcissism: 45 },
      patience: 85,
    }),
    decay: {},
    start: { ...body(70, 70, 85), social: 60, fun: 55, purpose: 55, respect: 60 },
    coins: 12,
  },
  {
    id: "tomas",
    name: "Tomas",
    vocation: "builder",
    craft: "build",
    blurb: "A gifted, restless craftsman who likes his work to be noticed.",
    colors: { hair: "#2a2a34", skin: "#d9a57a", shirt: "#2f9e9a", pants: "#34343e" },
    psyche: makePsyche({
      big5: { conscientiousness: 75, extraversion: 72, agreeableness: 38 },
      values: { achievement: 82, power: 70, stimulation: 66, benevolence: 35 },
      attachment: "anxious",
      dark: { narcissism: 72, machiavellianism: 40 },
      risk: 62,
    }),
    decay: {},
    start: { ...body(65, 60, 80), social: 55, fun: 50, purpose: 50, respect: 45 },
    coins: 14,
  },
  {
    id: "mo",
    name: "Mo",
    vocation: "cook",
    craft: "cook",
    blurb: "The village cook, a warm connector who notices who has not eaten.",
    colors: { hair: "#e8b83a", skin: "#e8b48a", shirt: "#4aa0e0", pants: "#4a4a58" },
    psyche: makePsyche({
      big5: { extraversion: 85, agreeableness: 85, neuroticism: 58 },
      values: { benevolence: 88, conformity: 70, tradition: 60, power: 25 },
      foundations: { care: 88, loyalty: 80 },
      attachment: "anxious",
      trust: 70,
    }),
    decay: {},
    start: { ...body(70, 60, 80), social: 40, fun: 60, purpose: 55, respect: 60 },
    coins: 10,
  },
  {
    id: "pip",
    name: "Pip",
    vocation: "farmer",
    craft: "farm",
    blurb: "Mo's sibling, a careful farmer who keeps a close eye on the food supply.",
    colors: { hair: "#6b3e26", skin: "#f5c9a0", shirt: "#e0584a", pants: "#3b4a8c" },
    psyche: makePsyche({
      big5: { neuroticism: 76, conscientiousness: 66, openness: 30 },
      values: { security: 86, tradition: 70, benevolence: 64, stimulation: 25 },
      foundations: { loyalty: 72 },
      attachment: "anxious",
      risk: 15,
      patience: 70,
    }),
    decay: { hunger: 1.3 },
    start: { ...body(45, 70, 85), social: 60, fun: 55, purpose: 55, respect: 55 },
    coins: 12,
  },
  {
    id: "juniper",
    name: "Juniper",
    vocation: "forager",
    craft: "forage",
    blurb: "A forager who knows the woods better than anyone and hates sitting still.",
    colors: { hair: "#2e2a3a", skin: "#c68a5e", shirt: "#58b858", pants: "#7a4a2a" },
    psyche: makePsyche({
      big5: { openness: 90, extraversion: 45, conscientiousness: 35 },
      values: { selfDirection: 86, stimulation: 80, universalism: 66, conformity: 25 },
      foundations: { liberty: 82 },
      attachment: "avoidant",
      risk: 70,
    }),
    decay: { energy: 1.1 },
    start: { ...body(65, 55, 90), social: 70, fun: 35, purpose: 55, respect: 55 },
    coins: 8,
  },
  {
    id: "bram",
    name: "Bram",
    vocation: "carpenter and village elder",
    craft: "build",
    blurb: "The oldest villager, a grumpy but kind carpenter who treasures his naps.",
    colors: { hair: "#b8b8c0", skin: "#f0c8a8", shirt: "#9a6ac8", pants: "#3a3a44" },
    psyche: makePsyche({
      big5: { agreeableness: 66, extraversion: 25, neuroticism: 45, openness: 38 },
      values: { tradition: 78, benevolence: 70, security: 66, stimulation: 22 },
      foundations: { sanctity: 62, authority: 60 },
      attachment: "secure",
      patience: 75,
    }),
    decay: { energy: 1.4 },
    start: { ...body(60, 65, 55), social: 70, fun: 60, purpose: 50, respect: 70 },
    coins: 18,
  },
  {
    id: "sable",
    name: "Sable",
    vocation: "shopkeeper",
    craft: "keep_shop",
    blurb: "A sharp, ambitious trader who runs the market stall and sets its prices.",
    colors: { hair: "#1c1c22", skin: "#e2b894", shirt: "#7a2438", pants: "#24242c" },
    psyche: makePsyche({
      big5: { agreeableness: 15, conscientiousness: 62, extraversion: 55 },
      values: { power: 86, achievement: 76, security: 60, benevolence: 20, universalism: 25 },
      foundations: { care: 25, fairness: 30 },
      attachment: "avoidant",
      dark: { machiavellianism: 85, narcissism: 60, psychopathy: 38 },
      patience: 80,
      risk: 70,
      trust: 28,
    }),
    decay: {},
    start: { ...body(60, 60, 80), social: 55, fun: 55, purpose: 50, respect: 55 },
    coins: 30,
  },
  {
    id: "hollis",
    name: "Hollis",
    vocation: "fisher",
    craft: "fish",
    blurb: "A charming fisher who loves a good time more than a hard day.",
    colors: { hair: "#c2762e", skin: "#f0c090", shirt: "#e8c83a", pants: "#3a5a8a" },
    psyche: makePsyche({
      big5: { conscientiousness: 15, extraversion: 72, agreeableness: 60 },
      values: { hedonism: 86, stimulation: 70, conformity: 25, achievement: 25 },
      attachment: "secure",
      patience: 15,
      risk: 60,
    }),
    decay: { energy: 0.9 },
    start: { ...body(60, 60, 75), social: 55, fun: 45, purpose: 55, respect: 55 },
    coins: 6,
  },
  {
    id: "odile",
    name: "Odile",
    vocation: "keeper of the old well shrine",
    craft: "shrine",
    blurb: "Keeper of the shrine at the old well, a guardian of custom and order.",
    colors: { hair: "#5a3a6a", skin: "#f4d2b4", shirt: "#ece4cc", pants: "#5a4a3a" },
    psyche: makePsyche({
      big5: { conscientiousness: 72, agreeableness: 45, openness: 25 },
      values: { tradition: 88, conformity: 82, security: 70, universalism: 15, stimulation: 20 },
      foundations: { sanctity: 90, authority: 85, loyalty: 85, liberty: 25 },
      attachment: "secure",
      trust: 45,
    }),
    decay: {},
    start: { ...body(65, 65, 80), social: 60, fun: 55, purpose: 60, respect: 65 },
    coins: 12,
  },
  {
    id: "lark",
    name: "Lark",
    vocation: "storyteller and musician",
    craft: "stories",
    blurb: "A storyteller and musician who would rather start a party than follow a rule.",
    colors: { hair: "#e86aa0", skin: "#d9a07a", shirt: "#f08cc8", pants: "#3a3a6a" },
    psyche: makePsyche({
      big5: { openness: 86, extraversion: 82, conscientiousness: 30 },
      values: { selfDirection: 86, universalism: 70, hedonism: 66, conformity: 18, tradition: 30 },
      foundations: { liberty: 90, authority: 15 },
      attachment: "secure",
      risk: 65,
    }),
    decay: {},
    start: { ...body(65, 60, 80), social: 55, fun: 45, purpose: 55, respect: 55 },
    coins: 8,
  },
]

/** Households share a house. The sixth house starts empty. */
export const HOUSEHOLDS: string[][] = [
  ["pip", "mo"],
  ["bram", "odile"],
  ["wren", "hollis"],
  ["tomas", "sable"],
  ["juniper", "lark"],
  [],
]

/** Founding relationships that differ from the default +0.2. */
export const FOUNDING_AFFINITY: [string, string, number][] = [
  ["wren", "tomas", -0.1],
  ["tomas", "wren", -0.1],
  ["pip", "mo", 0.7],
  ["mo", "pip", 0.7],
  ["odile", "lark", -0.2],
  ["lark", "odile", -0.05],
  ...["wren", "tomas", "mo", "pip", "juniper", "sable", "hollis", "odile", "lark"].map((id) => [id, "bram", 0.35] as [string, string, number]),
]
